# Generated by Django 4.0.3 on 2022-03-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_seen',
            field=models.BooleanField(default=False),
        ),
    ]
